// <auto-generated />
namespace MyVibes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Artist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Artist));
        
        string IMigrationMetadata.Id
        {
            get { return "202002132024190_Artist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
